// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9EMnkzyetz494TkRAJvUlHFKVe0INMcQ',
    appId: '1:769097617884:web:9dd7da68733e35e5f07f19',
    messagingSenderId: '769097617884',
    projectId: 'travelapp-45687',
    authDomain: 'travelapp-45687.firebaseapp.com',
    storageBucket: 'travelapp-45687.appspot.com',
    measurementId: 'G-9FJ4E3FTF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ-KDta81F2oC5ORM6t-KuozYelHYjn_s',
    appId: '1:769097617884:android:88fd6e8761120d8ff07f19',
    messagingSenderId: '769097617884',
    projectId: 'travelapp-45687',
    storageBucket: 'travelapp-45687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBFK21O4uMsj50eqY9GJ3WyO8UUkRR9k',
    appId: '1:769097617884:ios:3920a522a8ab1c61f07f19',
    messagingSenderId: '769097617884',
    projectId: 'travelapp-45687',
    storageBucket: 'travelapp-45687.appspot.com',
    iosBundleId: 'com.example.kidAsk',
  );
}
